# Generated by Django 2.2.8 on 2020-05-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200513_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='Test Product', max_length=200, unique=True),
        ),
    ]
