# Generated by Django 2.2.12 on 2020-09-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_orderitem_item_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('Sw', 'Sport wear'), ('Ow', 'Outwear'), ('Sm', 'Smartphone'), ('PC', 'Personal Computer')], default='S', max_length=2),
        ),
    ]
