# Generated by Django 2.2.12 on 2020-09-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200904_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Co', 'Coats'), ('Ja', 'Jackets'), ('S', 'Shirts'), ('Ts', 'T-shirts'), ('Sw', 'Sport wear'), ('Sh', 'Shoes'), ('Hat', 'Hats'), ('Ow', 'Outwear')], default='S', max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('O', 'ordinary'), ('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='P', max_length=1),
        ),
    ]
