# Generated by Django 2.2.8 on 2020-07-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200707_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stipe_charge_id',
            field=models.CharField(max_length=100),
        ),
    ]
