# Generated by Django 2.2.8 on 2020-07-07 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200708_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stipe_charge_id',
            new_name='stripe_charge_id',
        ),
    ]
