# Generated by Django 2.2.12 on 2020-09-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200905_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizes',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='S', max_length=3),
        ),
    ]
