# Generated by Django 2.2.12 on 2020-09-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200905_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizes',
            name='size',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
