# Generated by Django 2.2.12 on 2020-09-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200905_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizes',
            name='name',
            field=models.CharField(default='Size', max_length=20),
        ),
    ]
