# Generated by Django 2.2.12 on 2020-09-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sizes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizes',
            name='name',
            field=models.CharField(default='size', max_length=20),
        ),
    ]
