# Generated by Django 2.2.12 on 2020-09-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200907_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_size',
            field=models.ManyToManyField(to='core.Sizes'),
        ),
    ]
