# Generated by Django 2.2.12 on 2020-09-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_orderitem_item_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item_size',
            new_name='size',
        ),
    ]
