# Generated by Django 2.2.12 on 2020-09-07 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200907_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='size',
            new_name='item_size',
        ),
    ]
