# Generated by Django 2.2.12 on 2020-09-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200907_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['title', 'slug'], name='core_item_title_5d1ed3_idx'),
        ),
    ]
