# Generated by Django 2.2.8 on 2020-07-10 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200710_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Received',
            new_name='received',
        ),
    ]
