# Generated by Django 2.2.8 on 2020-07-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200710_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default=123456, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
