# Generated by Django 2.2.12 on 2020-10-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20201006_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category_type',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], max_length=5),
        ),
    ]
