# Generated by Django 2.2.12 on 2020-11-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20201119_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='othermarks',
            old_name='mark',
            new_name='name',
        ),
    ]
