# Generated by Django 2.2.12 on 2020-11-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20201119_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='othermarks',
            old_name='name',
            new_name='mark',
        ),
    ]
