# Generated by Django 2.2.12 on 2020-11-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20201119_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Coats', 'Coats'), ('Jackets', 'Jackets'), ('Shirts', 'Shirts'), ('T-shirts', 'T-shirts'), ('Sport-Wear', 'Sport wear'), ('Shoes', 'Shoes'), ('Hats', 'Hats'), ('Outwear', 'Outwear')], max_length=3),
        ),
    ]
