# Generated by Django 2.2.12 on 2020-11-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20201126_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Coats', 'Coats'), ('Jackets', 'Jackets'), ('Shirts', 'Shirts'), ('T-shirts', 'T-shirts'), ('Sport-wear', 'Sport wear'), ('Shoes', 'Shoes'), ('Hats', 'Hats'), ('Outwear', 'Outwear')], max_length=30),
        ),
    ]
