# Generated by Django 2.2.12 on 2021-03-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20210307_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='Item does not found', upload_to=''),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
