# Generated by Django 2.2.12 on 2021-03-07 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
    ]
