# Generated by Django 2.2.12 on 2021-03-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20210308_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='NoImageFound.png', upload_to=''),
        ),
    ]
