# Generated by Django 2.2.12 on 2021-03-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20210312_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='NoImageFound.png', null=True, upload_to=''),
        ),
    ]
