# Generated by Django 2.2.12 on 2021-03-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20210313_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='image',
            field=models.ImageField(blank=True, default='NoImageFound.png', null=True, upload_to=''),
        ),
    ]
