# Generated by Django 2.2.12 on 2021-03-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_todo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='other_marks',
            field=models.ManyToManyField(blank=True, null=True, to='core.OtherMarks'),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, to='core.Sizes'),
        ),
    ]
