# Generated by Django 2.2.12 on 2021-03-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20210321_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='other_marks',
            field=models.ManyToManyField(to='core.OtherMarks'),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.ManyToManyField(to='core.Sizes'),
        ),
    ]
