# Generated by Django 2.2.12 on 2021-03-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20210321_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='NoImageFound.png', null=True, upload_to=''),
        ),
    ]
