export const products = [
    {
      title: "Copeland",
      date: "2020-05-03",
      sku: 4490,
      price: 9503,
      color: [{ value: "Blue" }],
      size: [{ value: "Large" }],
    },
    {
      title: "Fleming",
      date: "2020-05-03",
      sku: 5005,
      price: 1698,
      color: [{ value: "Blue" }],
      size: [{ value: "Large" }],
    },
    {
      title: "Moses",
      date: "2020-08-01",
      sku: 9308,
      price: 3216,
      color: [{ value: "Blue" }],
      size: [{ value: "Medium" }],
    },
    {
      title: "Frey",
      date: "2020-08-01",
      sku: 5558,
      price: 2691,
      color: [{ value: "Blue" }],
      size: [{ value: "Large" }],
    },
    {
      title: "Chavez",
      date: "2020-08-01",
      sku: 7333,
      price: 3880,
      color: [{ value: "Red" }],
      size: [{ value: "Medium" }],
    },
    {
      title: "Warren",
      date: "2020-08-01",
      sku: 8483,
      price: 5757,
      color: [{ value: "Green" }],
      size: [{ value: "Medium" }],
    },
    {
      title: "Roman",
      date: "2020-06-04",
      sku: 458,
      price: 4732,
      color: [{ value: "Green" }],
      size: [{ value: "Medium" }],
    },
    {
      title: "Camacho",
      date: "2020-06-04",
      sku: 3089,
      price: 6979,
      color: [{ value: "Green" }],
      size: [{ value: "Medium" }],
    },
    {
      title: "Andrade",
      date: "2020-05-03",
      sku: 6344,
      price: 8863,
      color: [{ value: "Red" }],
      size: [{ value: "Large" }],
    },
    {
      title: "Hanson",
      date: "2020-05-03",
      sku: 4001,
      price: 3327,
      color: [{ value: "Blue" }],
      size: [{ value: "Large" }],
    },
    {
      title: "Miller",
      date: "2020-03-06",
      sku: 6188,
      price: 9636,
      color: [{ value: "Red" }],
      size: [{ value: "Medium" }],
    },
    {
      title: "Osborne",
      date: "2020-08-01",
      sku: 7214,
      price: 1277,
      color: [{ value: "Blue" }],
      size: [{ value: "Large" }],
    },
]